name: trie
description: A comprehensive Trie implementation in Dart, optimized for autocomplete.
version: 2.0.0
homepage: https://github.com/dark-mode/Trie
authors: [ Christopher Gong <christophergong@berkeley.edu>, Ankush Vangari <ankush@vangari.com> ]

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.17.11
